//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalWorldStore.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalWorldStoreDBEntities3 : DbContext
    {
        public DigitalWorldStoreDBEntities3()
            : base("name=DigitalWorldStoreDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles1 { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims1 { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins1 { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers1 { get; set; }
        public virtual DbSet<CartLists> CartLists1 { get; set; }
        public virtual DbSet<Categories> Categories1 { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails1 { get; set; }
        public virtual DbSet<Orders> Orders1 { get; set; }
        public virtual DbSet<Products> Products1 { get; set; }
    }
}
