//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalWorldStore.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int orderDetailId { get; set; }
        public int orderId { get; set; }
        public int productId { get; set; }
        public int quantity { get; set; }
        public decimal productUnitPrice { get; set; }
    
        public virtual Orders Order { get; set; }
        public virtual Products Product { get; set; }
    }
}
